server:
  port: 8080

spring:
  #mysql 配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.28.131:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  #redis 配置
  redis:
    #redis服务器地址
    host: 192.168.28.131
    #redis连接端口号
    port: 6379
    #redis连接密码
    password:
    #redis连接超时时间（毫秒）
    timeout: 2000


#  devtools:
#    restart:
#      enabled: true  #设置开启热部署
#      additional-paths: src/main/java #重启目录
#      exclude: WEB-INF/**
#    freemarker:
#      cache: false    #页面不加载缓存，修改即时生效

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#showSql
#logging:
#  level:
#    com:
#      axu:
#        spring_boot_mybatis:
#        mapper : debug

  #redis配置\


